import { Roboto } from "next/font/google";
import "./globals.css";
//components--------------------------------------------------------
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import StoreProvider from "./StoreProvider";

const roboto = Roboto({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<StoreProvider>
        <html lang="en">
        <body className={roboto.className}>
          <Header />
           {children}
          <Footer />
        </body>
      </html>
      </StoreProvider>
    );
}
